name: LevelDB Main Workflow

on:
  push:
    branches: [ main, master, develop, 'releases/**' ]
    paths-ignore:
      - 'compile_commands/**'   # prevent CI loop when we commit compile_commands.json
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: write
  pull-requests: write

jobs:
  leveldb-msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}   # cmake/ninja/strip/objcopy will come from /mingw64/bin

    env:
      BUILD_DIR: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true    # leveldb uses third_party; fetch submodules

      - name: Install MSYS2 toolchain
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-binutils
            mingw-w64-x86_64-snappy
            mingw-w64-x86_64-zlib

      - name: Configure (Ninja, export compile_commands.json)
        run: >
          cmake -S . -B "${BUILD_DIR}" -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          -DLEVELDB_BUILD_TESTS=ON
          -DLEVELDB_BUILD_BENCHMARKS=ON
          -DBUILD_SHARED_LIBS=OFF

      - name: Build
        run: cmake --build "${BUILD_DIR}" --config Release -j2

      - name: Test
        run: ctest --output-on-failure -C Release --test-dir "${BUILD_DIR}"

      # --- Produce full & stripped bundles for Ghidra ---
      - name: Package (full + stripped + symbols)
        run: |
          set -euo pipefail

          mkdir -p out/full/bin out/full/lib out/full/include/leveldb
          mkdir -p out/stripped/bin out/stripped/lib
          mkdir -p out/symbols

          # Headers
          [ -d include/leveldb ] && cp -R include/leveldb/* out/full/include/leveldb/ || true

          # Libraries (static or shared)
          # copy typical names from the build tree (ignore CMakeFiles)
          find "${BUILD_DIR}" -maxdepth 3 -type f -not -path '*/CMakeFiles/*' \
            \( -name 'libleveldb*.a' -o -name 'leveldb*.a' -o -iname 'leveldb*.dll' -o -iname 'leveldb*.lib' \) \
            -exec cp -f {} out/full/lib/ \; || true

          # Binaries (tests/bench/utils)
          find "${BUILD_DIR}" -type f -not -path '*/CMakeFiles/*' \
            \( -iname '*.exe' -o -iname '*.dll' \) \
            -exec cp -f {} out/full/bin/ \; || true

          # Stripped copies start from full
          cp -f out/full/lib/* out/stripped/lib/ 2>/dev/null || true
          cp -f out/full/bin/* out/stripped/bin/ 2>/dev/null || true

          # Strip static libs
          find out/stripped/lib -type f -name '*.a' -exec strip -g {} \; || true

          # Strip EXE/DLL & create separate .debug files (GNU style)
          shopt -s nullglob
          for f in out/stripped/bin/*.exe out/stripped/bin/*.dll; do
            base="$(basename "$f")"
            if [ -f "out/full/bin/$base" ]; then
              objcopy --only-keep-debug "out/full/bin/$base" "out/symbols/$base.debug" || true
            else
              objcopy --only-keep-debug "$f" "out/symbols/$base.debug" || true
            fi
            strip --strip-debug "$f" || true
            if [ -f "out/symbols/$base.debug" ]; then
              objcopy --add-gnu-debuglink="out/symbols/$base.debug" "$f" || true
            fi
          done

          echo "---- FULL ----";     find out/full     -maxdepth 4 -type f -print || true
          echo "---- STRIPPED ----"; find out/stripped -maxdepth 4 -type f -print || true
          echo "---- SYMBOLS ----";  find out/symbols  -maxdepth 4 -type f -print || true

      - name: Upload artifact (full symbols)
        uses: actions/upload-artifact@v4
        with:
          name: ghidra-full-windows-msys2-Release
          path: out/full/**
          if-no-files-found: warn
          retention-days: 30

      - name: Upload artifact (stripped)
        uses: actions/upload-artifact@v4
        with:
          name: ghidra-stripped-windows-msys2-Release
          path: out/stripped/**
          if-no-files-found: warn
          retention-days: 30

      - name: Upload artifact (separate .debug symbols)
        uses: actions/upload-artifact@v4
        with:
          name: ghidra-symbols-windows-msys2-Release
          path: out/symbols/**
          if-no-files-found: warn
          retention-days: 30

      # --- Auto-commit compile_commands.json (robust when unchanged) ---
      - name: Commit compile_commands.json into repo
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')
        shell: pwsh
        env:
          TARGET_DIR: compile_commands/windows-msys2
          BUILD_DIR: ${{ env.BUILD_DIR }}
        run: |
          $ErrorActionPreference = "Stop"

          $src = Join-Path $env:GITHUB_WORKSPACE "$env:BUILD_DIR\compile_commands.json"
          if (!(Test-Path $src)) {
            Write-Host "compile_commands.json not found at $src"
            exit 0
          }

          $outDir = Join-Path $env:GITHUB_WORKSPACE $env:TARGET_DIR
          New-Item -ItemType Directory -Force -Path $outDir | Out-Null
          Copy-Item $src (Join-Path $outDir 'compile_commands.json') -Force

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git config --global --add safe.directory $env:GITHUB_WORKSPACE

          git add "$env:TARGET_DIR/compile_commands.json"
          git diff --cached --quiet
          if ($LASTEXITCODE -ne 0) {
            git commit -m "[skip ci] update compile_commands.json ($env:TARGET_DIR)"
            git push
          } else {
            Write-Host "No changes in compile_commands.json; nothing to commit."
          }
          exit 0

      # SonarCloud scan using compile_commands.json (no org/key in args; read from sonar-project.properties)
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.projectBaseDir=.
            --define sonar.sources=.
            --define sonar.exclusions=**/third_party/**,**/.scannerwork/**,**/${{ env.BUILD_DIR }}/**
            --define sonar.cfamily.compile-commands=${{ env.BUILD_DIR }}/compile_commands.json
            --define sonar.verbose=true
